import { makeStyles } from "@material-ui/core";

const useStyles = makeStyles(theme =>({
    main:{
        backgroundColor: '#ffffff',
        textAlign: center,
        position: relative,
        width: '23.75rem',
        height: '36.375rem',
        boxSizing: border-box,
        borderRadius: '0.5rem',
        border: '0.063rem solid #DFE0EB',
        margin:'0px auto',
    },
    logo: {
        position: relative,
        width: '3rem',
        height: '3rem',
        display: flex,
        justifyContent: center,
        backgroundColor: '#3751FF',
        paddingLeft: '0.09rem',
        marginTop: '2.5rem',
        marginLeft: '44%',
        borderRadius: '2.5rem',
        alignItems: center,
    },
    d: {
        background: linear-gradient('143.7deg, rgba(255, 255, 255, 0.7) 0%, #FFFFFF 100%'),
        width: '1.125rem',
        height: '1.313rem',
        borderTopRightRadius: '0.6rem',
        borderBottomRightRadius: '0.6rem',
    },
    logoL: {
        width: '19.75rem',
        height: '1.5rem',
        display: 'inline-block',
        marginTop: '0.75rem',
        textAlign: center,
        color: '#A4A6B3',
        opacity: 0.7,
        fontFamily: 'Mulish',
        fontStyle: normal,
        fontWeight: 700,
        fontSize: '1.188rem',
        lineHeight: '1.5rem',
        letterSpacing: '0.025rem',
    },
    tit: {
        display: inline-block,
        width: '19.75rem',
        height: '1.875rem',
        marginTop: '2rem',
        fontFamily: 'Mulish',
        fontStyle: normal,
        fontWeight:bolder,
        fontSize: '1.5rem',
        lineHeight: '1.875rem',
        textAlign: center,
        letterSpacing: '0.019rem',
        color: '#252733',
    },
    comment: {
        display: inline-block,
        width: '19.75rem',
        height: '1.25rem',
        marginTop: '0.75rem',
        marginBottom: '1.5rem',
        fontFamily: 'Mulish',
        fontStyle: normal,
        fontWeight: 400,
        fontSize: '0.875rem',
        lineHeight: '1.25rem',
        textAlign: center,
        letterSpacing: '0.019rem',
        color: '#9FA2B4',
    },
    con: {
        marginLeft: '50px',
        width: '18rem',
        marginTop: '1.5rem',
        padding: '0rem',
        display: flex,
        flexDirection: column,
        alignItems: center,
    },
    label: {
        width: '19.75rem',
        height: '1rem',
        marginLeft: '2rem',
        fontFamily: 'Mulish, sans-serif',
        fontStyle: normal,
        fontWeight: bolder,
        fontSize: '0.75rem',
        lineHeight: '0.938rem',
        letterSpacing: '0.019rem',
        textTransform: uppercase,
        textAlign: justify,
    },
    in: {
        textAlign: left,
        alignItems: center,
        width: '18rem',
        height: '2.625rem',
        padding: '0.688rem 1rem',
        boxSizing: 'border-box',
        background: '#FCFDFE',
        border: '0.063rem solid #F0F1F7',
        borderRadius: '8px',
    },
    eyeB: {
        position: absolute,
        right: '3.6rem',
        bottom: '11.6rem',
        height: '18px',
        width: '21px',
        border: none,
    },
    eye: {
        opacity: 0.3,
        height: '100%',
        width: '100%',
    },
    p: {
        textDecoration: none,
        color: '#9FA2B4',
        fontFamily: 'Mulish',
        fontStyle: normal,
        fontWeight: 400,
        fontSize: '0.875rem',
        lineHeight: '1.25rem',
    },
    a: {
        textDecoration: none,
        color: '#9FA2B4',
        fontFamily: 'Mulish',
        fontStyle: normal,
        fontWeight: 400,
        fontSize: '0.875rem',
        lineHeight: '1.25rem',
    },
    singup: {
        textDecoration: none,
        fontFamily: 'Mulish',
        fontStyle: normal,
        letterSpacing: '0.2px',
        fontSize: '0.875rem',
        color: '#3751FF',
        fontWeight: 600,
        lineHeight: '1.25rem',
    },
    forgot: {
        position: absolute,
        right: '3.125rem',
        top: '60%',
        fontWeight: 400,
        fontSize: '0.625rem',
        lineHeight: '0.813rem',
        textAlign: right,
        letterSpacing: '0.1px',
    },
    button: {
        alignItems: center,
        textAlign: center,
        width: '18rem',
        height: '3rem',
        backgroundColor: '#3751FF',
        border: none,
        color: '#fff',
        fontFamily: 'Mulish',
        fontStyle: normal,
        fontWeight: 600,
        fontSize: '14px',
        lineHeight: '20px',
        borderRadius: '8px',
        boxShadow: '0rem 0.25rem 0.75rem rgba(55, 81, 255, 0.24)',
        marginTop: '24px',
    },
}));
export default useStyles;